version: '2'
services:
    auction_platform-app:
        image: auction_platform
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://auction_platform-postgresql:5432/auction_platform
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    auction_platform-postgresql:
        extends:
            file: postgresql.yml
            service: auction_platform-postgresql
